name: Sonar Cloud
on: 
  push:
    paths-ignore:
      - '.github/workflows/**'
      - 'p2.yml'
      
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types:
      - completed
  
jobs:
  Scan:
    name: static-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR }}
